### ISSUE TITLE
pitanje stranice primjera

### ISSUE THREAD

**Issue by vvacek** [Bikonja/generator-barkoda-uplatnica#4]
sorry ako ovo nije mjesto/nacin ali nisam znao kako drukcije

koristio sam zadnjih mjeseci stranicu primjera koristenja za izradu bar koda, odlicno, fakat mi je falilo tako nesto. no zadnjih desetak dana mi ne radi, dropdown meniji se ne pojavljuju i nece generirat bar kod?

**Comment by Bikonja** [comment]
@vvacek pravo je mjesto, medjutim nisam vec dugo u hrvatskoj i ne odrzavam ovo vec dugo. Brzinski pogled izgleda mi da moram podesit neke stvari za nove sigurnosne postavke, ali ne znam kad cu imat vremena za to, medjutim predlazem ovaj fork baziran na mojem repo-u koji je aktivniji i unaprijedjen: https://ivoras.github.io/generator-barkoda-uplatnica/

Ostavit cu ovaj issue otvoren za slucaj da nekad uspijem popravit cisto da radi, ali definitivno preporucam aktivniji fork gore ili druge opcije s obzirom da se ne bavim aktivno vise s ovim.

**Comment by vvacek** [comment]
sve jasno, razumijem. hvala ti za preporuku, i hvala za cijeli trud oko ovoga :)

**Comment by Bikonja** [comment]
Hvala na komentaru, jako je lijepo vidjeti da je ljudima dobro doslo :)
Bacio sam pogled malo blizi i prethodni komad koda koji je u linkanom pull requestu dodan je dodao ovisnost o Node.js-u koju nisam primjetil kad sam zatvorio pull request.
Popravio sam da radi opet, ali IBAN validacija nece radit bez Node.js-a.
